#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
    systemctl stop stassh-authorized-keys.path
    systemctl disable stassh-authorized-keys.path
fi

if [ "$1" = "purge" ]; then
    rm -rf /etc/stassh
    rm -rf /var/lib/stassh

    systemctl stop stassh-authorized-keys.path
    systemctl disable stassh-authorized-keys.path
fi

#DEBHELPER#


